version: '3.8'
services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: "http://localhost:5000"
    depends_on:
      - backend
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
